### ISSUE TITLE
Optimization with blas operations

### ISSUE THREAD

**Issue by rreusser** [scijs/ndarray-cholesky-factorization#1]
Oops! I checked out a branch and just happened to name it the same thing! Sorry if I mixed things up/interfered! Looks great though. Just noticed that the inner product could maybe be replaced with:

```
var s = blas1.dot(L.pick(i,null).hi(j), L.pick(j,null).hi(j));
```

**Comment by rreusser** [comment]
Oh wait, I didn't push yet… good, so no harm no foul… Okay. (Dog was in the process of peeing in the wrong spot, so was distracted.) But yeah, I think that line should optimize things ever so slightly.

**Comment by Planeshifter** [comment]
Sounds good, will replace the dot product and push a new version in a few minutes.
